### ISSUE TITLE
sandpack-cdn-v2.codesandbox.io caching 500's for too long. 

### ISSUE THREAD

**Issue by nicksrandall** [codesandbox/sandpack-cdn#13]
When I push a new version of a package to NPM and then try to use it in sandpack (nodebox), I get an initial 500 error from `https://sandpack-cdn-v2.codesandbox.io` presumably because that package's latest version hasn't propagated to that service yet. That said, this response is cached by the CDN for 1 hour making it impossible to use my package for a whole hour even though a minute or two later, the package is available. 

It would be great if we could not cache the 500 responses (or use a much smaller cache window).

**Comment by danilowoz** [comment]
Hey @DeMoorJasper, could you take a look at this issue?

**Comment by DeMoorJasper** [comment]
Yes, will change it, this was mostly a legacy thing but now that performance is incredibly good and the cdn barely uses any ressources we can definitely lower this ttl. Will set it to 5 minutes or something

**Comment by DeMoorJasper** [comment]
Fixed in 01fd2b894884fca5fdd83b734af53968b33b593e
